### ISSUE TITLE
Ошибки текста

### ISSUE THREAD

**Issue by BaroH4er** [GolosChain/registration-frontend#1]
## Использование кириллицы в поле "Имя аккаунта"

**Проблема:** при использовании кириллицы в поле "Имя аккаунта", текст ошибки не соответствует действительности. 
![image.png](https://images.zenhubusercontent.com/5a6f31974b5806bc2bc4b26e/53715c51-b62e-4739-8aca-dd4a51188b8a)

- [x] FIXED

**Воспроизвести:** 

1. Открыть https://reg.golos.io/
2. Добавить символ на кириллице в поле "Имя аккаунта".

**Результат:** Под полем "Имя аккаунта" появляется красный текст "Ник должен начинаться с буквы".
**Ожидаемый результат:** Под полем "Имя аккаунта" появляется красный текст "Имя аккаунта должно быть на латинице/англ".

**Comment by BaroH4er** [comment]
Новый текст для страницы регистрации: 

https://docs.google.com/spreadsheets/d/1U2x-zSGd9JCvdmv3q5ODR92snkImAwHRsUG3m0MPGBY/edit#gid=1904240521

**Comment by BaroH4er** [comment]
### Ошибка при использовании первым символом цифры в имени. 
**Проблема:** Текст ошибки не соответствует наименованию поля.
![image](https://user-images.githubusercontent.com/21989598/45690490-18f81980-bb5f-11e8-847d-9724ce6a6aa6.png)

- [ ] FIXED

**Решение:** Заменить "Ник" на "Имя".

<hr/>

### Введите номер вашего телефона (без кода страны)

**Проблема:** не хватает подсказки "(без кода страны)"

- [ ] FIXED

![image](https://user-images.githubusercontent.com/21989598/45690892-11854000-bb60-11e8-99b3-af036288f153.png)

**Решение:** добавить подсказку "(без кода страны)".

<hr/>

**Comment by BaroH4er** [comment]
Заменить "должен" на "должно"
![image](https://user-images.githubusercontent.com/21989598/46010637-19972f80-c0cc-11e8-979f-3106623aa4bf.png)

**Comment by Bacher** [comment]
Точно)

**Comment by BaroH4er** [comment]
Done
