### ISSUE TITLE
Поле ввода имени

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/registration-frontend#33]
Поле ввода имени:
- [ ] добавить текстовое предупреждение при вводе имени не латиницей:
>  Для ввода имени используйте латиницу
>  Please use Latin characters in account name

- [ ] добавить текстовое предупреждение при вводе имени с пробелом:
> Для ввода имени не используйте пробел, пожалуйста
>Please do not use a space to enter the name

**Comment by Bacher** [comment]
По договоренности было решено показывать сообщение "Используйте только английские буквы, цифры, точку, тире." сразу при попытке ввода неправильного символа.

**Comment by daryasattarova** [comment]
при попытке поставить пробел появляется не та текстовка
![image](https://user-images.githubusercontent.com/42342756/46787509-7cc9c880-cd40-11e8-841c-795b85a30386.png)

**Comment by daryasattarova** [comment]
не по центру отображается текст в Mozilla
![image](https://user-images.githubusercontent.com/42342756/46787796-33c64400-cd41-11e8-8949-67b0c8e5ea43.png)

**Comment by Bacher** [comment]
> 1. при попытке поставить пробел появляется не та текстовка.
Это нормально, решили одну текстовку использовать для обоих случаев.

**Comment by Bacher** [comment]
> не по центру отображается текст в Mozilla

Поправил
