### ISSUE TITLE
Поле выбора кода страны

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/registration-frontend#34]
![image](https://user-images.githubusercontent.com/30616421/46533155-e9a61400-c8a3-11e8-9640-54838aff968f.png)
- [ ] В поле выбора кода страны добавить все страны
- [ ] Россию, Украину, Беллорусию, Казахстан,  США, по умолчанмю ставить первыми в списке стран

**Comment by Bacher** [comment]
Все все прям?

**Comment by Bacher** [comment]
Zimbabwe +263 тоже?

**Comment by jevgenika** [comment]
Конечно, все страны

**Comment by Bacher** [comment]
Может дать вариант Другое (Other) и там давать ввести любой телефон? Номер валидации у них всё равно будет один и тот же. (+1 (256) 358-7178)

**Comment by Bacher** [comment]
Текущий список не особо корректен
![image](https://user-images.githubusercontent.com/2598671/46613259-76a6d280-cb1b-11e8-9349-080f5d0fc81b.png)

**Comment by Bacher** [comment]
В целом, если делать список, то предлагаю взять у Facebook:
![image](https://user-images.githubusercontent.com/2598671/46614127-b2db3280-cb1d-11e8-9609-e18bb09fe882.png)
