### ISSUE TITLE
второй шаг регистрации, страница ожидания подтверждения номера: поправить отображени введенного номера

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/registration-frontend#36]
второй шаг регистрации, страница ожидания подтверждения номера: поправить отображени введенного номера
![image](https://user-images.githubusercontent.com/30616421/46533873-7f42a300-c8a6-11e8-9854-7eb8ab770732.png)
- [ ] заменить ввид введенного номера на ввод типа +(370) 605-342-55

**Comment by Bacher** [comment]
Сошлись на формате `+370 6053-42-55`. Так как телефон выбивается из формата по длине.
