### ISSUE TITLE
Обновить тексты "регистрации"

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/registration-frontend#4]
@NickShtefan commented on [Wed Sep 12 2018](https://github.com/GolosChain/registration-service/issues/2)

[Ссылка на тексты](https://docs.google.com/spreadsheets/d/1U2x-zSGd9JCvdmv3q5ODR92snkImAwHRsUG3m0MPGBY/edit?ts=5b97cdee#gid=1248401032)

**Comment by Bacher** [comment]
Готово, пул-реквест общий.

**Comment by BaroH4er** [comment]
Done
