### ISSUE TITLE
Добавить предупреждение о незаполненным чекбоксе

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/registration-frontend#41]
Нет текстого предупреждение о незаполненном чек боксе.
Стр генерации пароля, сохранения пароля

Добавить текст, шрифт красным:
Пожалуйста, заполните все необходимые поля.

Check all required boxes to proceed with registration.

**Comment by Bacher** [comment]
![image](https://user-images.githubusercontent.com/2598671/46607575-22472700-cb0a-11e8-81d5-edd7085b31eb.png)
