### ISSUE TITLE
На iPhone 5 не влезает верстка

### ISSUE THREAD

**Issue by Bacher** [GolosChain/registration-frontend#72]
На iPhone 5 не влезает верстка

**Comment by daryasattarova** [comment]
https://github.com/GolosChain/tolstoy/issues/1035
поправить верстку шапки при условии не авторизированного пользователя
1. близко расположен юзернейм и полное имя
![inkedphoto_2018-10-24_13-33-44_li](https://user-images.githubusercontent.com/42342756/47425533-46a23500-d793-11e8-8133-9d7f29d0907e.jpg)
2. иконка накладывается на кнопку "назад"
![inkedphoto_2018-10-24_13-33-44 3 _li](https://user-images.githubusercontent.com/42342756/47425552-56217e00-d793-11e8-860d-b4512825c16f.jpg)
3. экран редактирования поста
![photo_2018-10-24_13-33-44 2](https://user-images.githubusercontent.com/42342756/47425561-5f124f80-d793-11e8-8537-0a52b43c08bb.jpg)

**Comment by Bacher** [comment]
Не не, тут issue про верстку страницы регистрации. Основной сайт в другом репозитории.

**Comment by daryasattarova** [comment]
> [GolosChain/tolstoy#1035](https://github.com/GolosChain/tolstoy/issues/1035)
> поправить верстку шапки при условии не авторизированного пользователя
> 
> 1. близко расположен юзернейм и полное имя
>    ![inkedphoto_2018-10-24_13-33-44_li](https://user-images.githubusercontent.com/42342756/47425533-46a23500-d793-11e8-8133-9d7f29d0907e.jpg)
> 2. иконка накладывается на кнопку "назад"
>    ![inkedphoto_2018-10-24_13-33-44 3 _li](https://user-images.githubusercontent.com/42342756/47425552-56217e00-d793-11e8-860d-b4512825c16f.jpg)
> 3. экран редактирования поста
>    ![photo_2018-10-24_13-33-44 2](https://user-images.githubusercontent.com/42342756/47425561-5f124f80-d793-11e8-8537-0a52b43c08bb.jpg)
